//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sims.Toolkit.Api.Plugin.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GamePacks {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GamePacks() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sims.Toolkit.Api.Assets.Properties.GamePacks", typeof(GamePacks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base Game.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New/Unknown.
        /// </summary>
        public static string EP00 {
            get {
                return ResourceManager.GetString("EP00", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get to Work.
        /// </summary>
        public static string EP01 {
            get {
                return ResourceManager.GetString("EP01", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get Together.
        /// </summary>
        public static string EP02 {
            get {
                return ResourceManager.GetString("EP02", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to City Living.
        /// </summary>
        public static string EP03 {
            get {
                return ResourceManager.GetString("EP03", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cats &amp; Dogs.
        /// </summary>
        public static string EP04 {
            get {
                return ResourceManager.GetString("EP04", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string EP05 {
            get {
                return ResourceManager.GetString("EP05", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get Famous.
        /// </summary>
        public static string EP06 {
            get {
                return ResourceManager.GetString("EP06", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Island Living.
        /// </summary>
        public static string EP07 {
            get {
                return ResourceManager.GetString("EP07", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discover University.
        /// </summary>
        public static string EP08 {
            get {
                return ResourceManager.GetString("EP08", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eco Lifestyle.
        /// </summary>
        public static string EP09 {
            get {
                return ResourceManager.GetString("EP09", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Snowy Escape.
        /// </summary>
        public static string EP10 {
            get {
                return ResourceManager.GetString("EP10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cottage Living.
        /// </summary>
        public static string EP11 {
            get {
                return ResourceManager.GetString("EP11", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Holiday Celebration.
        /// </summary>
        public static string FP01 {
            get {
                return ResourceManager.GetString("FP01", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outdoor Retreat.
        /// </summary>
        public static string GP01 {
            get {
                return ResourceManager.GetString("GP01", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spa Day.
        /// </summary>
        public static string GP02 {
            get {
                return ResourceManager.GetString("GP02", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dine Out.
        /// </summary>
        public static string GP03 {
            get {
                return ResourceManager.GetString("GP03", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vampires.
        /// </summary>
        public static string GP04 {
            get {
                return ResourceManager.GetString("GP04", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parenthood.
        /// </summary>
        public static string GP05 {
            get {
                return ResourceManager.GetString("GP05", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jungle Adventure.
        /// </summary>
        public static string GP06 {
            get {
                return ResourceManager.GetString("GP06", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Strangerville.
        /// </summary>
        public static string GP07 {
            get {
                return ResourceManager.GetString("GP07", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Realm of Magic.
        /// </summary>
        public static string GP08 {
            get {
                return ResourceManager.GetString("GP08", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Star Wars Journey to Batuu.
        /// </summary>
        public static string GP09 {
            get {
                return ResourceManager.GetString("GP09", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dream Home Decorator.
        /// </summary>
        public static string GP10 {
            get {
                return ResourceManager.GetString("GP10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Luxury Party Stuff.
        /// </summary>
        public static string SP01 {
            get {
                return ResourceManager.GetString("SP01", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Perfect Patio Stuff.
        /// </summary>
        public static string SP02 {
            get {
                return ResourceManager.GetString("SP02", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cool Kitchen Stuff.
        /// </summary>
        public static string SP03 {
            get {
                return ResourceManager.GetString("SP03", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spooky Stuff.
        /// </summary>
        public static string SP04 {
            get {
                return ResourceManager.GetString("SP04", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Movie Hangout Stuff.
        /// </summary>
        public static string SP05 {
            get {
                return ResourceManager.GetString("SP05", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Romantic Garden Stuff.
        /// </summary>
        public static string SP06 {
            get {
                return ResourceManager.GetString("SP06", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kids Room Stuff.
        /// </summary>
        public static string SP07 {
            get {
                return ResourceManager.GetString("SP07", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backyard Stuff.
        /// </summary>
        public static string SP08 {
            get {
                return ResourceManager.GetString("SP08", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vintage Glamour Stuff.
        /// </summary>
        public static string SP09 {
            get {
                return ResourceManager.GetString("SP09", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bowling Night Stuff.
        /// </summary>
        public static string SP10 {
            get {
                return ResourceManager.GetString("SP10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fitness Stuff.
        /// </summary>
        public static string SP11 {
            get {
                return ResourceManager.GetString("SP11", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toddler Stuff.
        /// </summary>
        public static string SP12 {
            get {
                return ResourceManager.GetString("SP12", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Landry Day Stuff.
        /// </summary>
        public static string SP13 {
            get {
                return ResourceManager.GetString("SP13", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My First Pet Stuff.
        /// </summary>
        public static string SP14 {
            get {
                return ResourceManager.GetString("SP14", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moshino Stuff.
        /// </summary>
        public static string SP15 {
            get {
                return ResourceManager.GetString("SP15", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tiny Living Stuff.
        /// </summary>
        public static string SP16 {
            get {
                return ResourceManager.GetString("SP16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nifty Knitting Stuff.
        /// </summary>
        public static string SP17 {
            get {
                return ResourceManager.GetString("SP17", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paranormal Stuff.
        /// </summary>
        public static string SP18 {
            get {
                return ResourceManager.GetString("SP18", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Throwback Fit Kit.
        /// </summary>
        public static string SP20 {
            get {
                return ResourceManager.GetString("SP20", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country Kitchen Kit.
        /// </summary>
        public static string SP21 {
            get {
                return ResourceManager.GetString("SP21", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bust The Dust Kit.
        /// </summary>
        public static string SP22 {
            get {
                return ResourceManager.GetString("SP22", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Courtyard Oasis Kit.
        /// </summary>
        public static string SP23 {
            get {
                return ResourceManager.GetString("SP23", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Industrial Loft Kit.
        /// </summary>
        public static string SP25 {
            get {
                return ResourceManager.GetString("SP25", resourceCulture);
            }
        }
    }
}
