name: Reports

on:
  workflow_run:
    workflows: [ 'Build-Windows' ]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: sims-toolkit-windows-xunit-results
          fail-on-error: true
          name: Sims Toolkit Windows Tests
          path: '*.trx'
          reporter: dotnet-trx
